
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
      target: final
      tags:
        - ietf_hackathon-client:latest
    networks:
      source:
        ipv6_address: 2001:db8:0:1::11
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON

  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
      target: final
      tags:
        - ietf_hackathon-server:latest
    networks:
      destination:
        ipv6_address: 2001:db8:0:2::5
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON

  source:
    build:
      context: .
      dockerfile: ./docker/source.Dockerfile
      target: final
      tags:
        - ietf_hackathon-source:latest
    networks:
      source:
        ipv6_address: 2001:db8:0:1::2

      control:
        ipv6_address: 2001:db8:0:5::9
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON

  destination:
    build:
      context: .
      dockerfile: ./docker/destination.Dockerfile
      target: final
      tags:
        - ietf_hackathon-destination:latest
    networks:
      destination:
        ipv6_address: 2001:db8:0:2::2

      control:
        ipv6_address: 2001:db8:0:5::3

    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON
  middle-base:
    build:
      context: .
      dockerfile: ./docker/middle.Dockerfile
      tags:
        - ietf_hackathon-middle-base:latest
      target: final
    profiles:
      - base


  middle1:
    image: ietf_hackathon-middle-base:latest
    networks:
      middle1:
        ipv6_address: 2001:db8:0:3::2
      source:
        ipv6_address: 2001:db8:0:1::3

      control:
        ipv6_address: 2001:db8:0:5::4
    cap_add:
      - BPF    
      - NET_ADMIN
      - PERFMON
  middle2:
    image: ietf_hackathon-middle-base:latest
    networks:
      middle2:
        ipv6_address: 2001:db8:0:4::2
      source:
        ipv6_address: 2001:db8:0:1::4
      
      control:
        ipv6_address: 2001:db8:0:5::5
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON

  middle3:
    image: ietf_hackathon-middle-base:latest
    networks:
      middle1:
        ipv6_address: 2001:db8:0:3::3

      control:
        ipv6_address: 2001:db8:0:5::6
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON

  middle4:
    image: ietf_hackathon-middle-base:latest
    networks:
      middle1:
        ipv6_address: 2001:db8:0:3::4
      middle2:
        ipv6_address: 2001:db8:0:4::4
      destination:
        ipv6_address: 2001:db8:0:2::3

      control:
        ipv6_address: 2001:db8:0:5::7
    cap_add:
      - BPF 
      - NET_ADMIN 
      - PERFMON
  middle5:
    image: ietf_hackathon-middle-base:latest
    networks:
      middle2:
        ipv6_address: 2001:db8:0:4::5
      destination:
        ipv6_address: 2001:db8:0:2::4

      control:
        ipv6_address: 2001:db8:0:5::8
    cap_add:
      - BPF
      - NET_ADMIN
      - PERFMON

  control-base:
    build:
      context: .
      dockerfile: ./docker/control.Dockerfile
      target: final
      tags:
        - ietf_hackathon-control_plane:latest

    profiles:
      - base

  control1:
    image: ietf_hackathon-control_plane:latest
    networks:
      control:
        ipv6_address: 2001:db8:0:5::2



networks:
  source:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:0:1::/64
    driver_opts:
      com.docker.network.container_iface_prefix: src

  destination:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:0:2::/64
    driver_opts:
      com.docker.network.container_iface_prefix: dst   

  middle1:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:0:3::/64
    driver_opts:
      com.docker.network.container_iface_prefix: mid1

  middle2:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:0:4::/64
    driver_opts:
      com.docker.network.container_iface_prefix: mid2

  control:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:0:5::/64
    driver_opts:
      com.docker.network.container_iface_prefix: ctrl
