global:
    config:
        as: 64513
        router-id: 192.168.1.3

neighbors:
    - config:
        peer-as: 64512
        neighbor-address: 2001:db8:0:5::2
      afi-safis:
        - config:
            afi-safi-name: ipv6-flowspec
    - config:
        peer-as: 64514
        neighbor-address: 2001:db8:0:5::3
      afi-safis:
        - config:
            afi-safi-name: ipv6-flowspec

