//Code generated by json2c
#pragma once
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#include <stdalign.h>
#endif
typedef enum BGPFlowSpecType {
    BGPFlowSpecType_UNKNOWN = 0,
    BGPFlowSpecType_DST_PREFIX = 1,
    BGPFlowSpecType_SRC_PREFIX = 2,
    BGPFlowSpecType_IP_PROTO = 3,
    BGPFlowSpecType_PORT = 4,
    BGPFlowSpecType_DST_PORT = 5,
    BGPFlowSpecType_SRC_PORT = 6,
    BGPFlowSpecType_ICMP_TYPE = 7,
    BGPFlowSpecType_ICMP_CODE = 8,
    BGPFlowSpecType_TCP_FLAG = 9,
    BGPFlowSpecType_PKT_LEN = 10,
    BGPFlowSpecType_DSCP = 11,
    BGPFlowSpecType_IP_FRAGMENT = 12,
    BGPFlowSpecType_FLOW_LABEL = 13,
    BGPFlowSpecType_AND = 0xf0,
    BGPFlowSpecType_OR = 0xf1,
    BGPFlowSpecType_EQ = 0xf2,
    BGPFlowSpecType_NEQ = 0xf3,
    BGPFlowSpecType_GT = 0xf4,
    BGPFlowSpecType_GTE = 0xf5,
    BGPFlowSpecType_LS = 0xf6,
    BGPFlowSpecType_LSE = 0xf7,
    BGPFlowSpecType_TRUE = 0xf8,
    BGPFlowSpecType_FALSE = 0xf9,
    BGPFlowSpecType_PREFIX_VALUE = 0xfa,
    BGPFlowSpecType_VALUE = 0xfb,
} BGPFlowSpecType;

